package com.semanticvault.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.SQLDelete;
import org.hibernate.annotations.SQLRestriction;

/**
 * Represents a high-dimensional vector embedding generated by an embedding model.
 */
@Entity
@Table(name = "vector_embeddings")
@SQLDelete(sql = "UPDATE vector_embeddings SET deleted = true WHERE id = ?")
@SQLRestriction("deleted = false")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class VectorEmbedding extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "chunk_id", nullable = false, unique = true)
    private DocumentChunk chunk;

    @Column(name = "model_name", nullable = false)
    private String modelName;

    @Column(nullable = false)
    private int dimensions;

    @Column(name = "vector_data", columnDefinition = "bytea")
    private byte[] vectorData;

    /**
     * Converts float[] to byte[] for storage.
     */
    public void setVectorFromFloats(float[] values) {
        if (values == null) {
            this.vectorData = null;
            return;
        }
        java.nio.ByteBuffer buffer = java.nio.ByteBuffer.allocate(values.length * 4);
        for (float v : values) {
            buffer.putFloat(v);
        }
        this.vectorData = buffer.array();
        this.dimensions = values.length;
    }

    /**
     * Converts stored byte[] back to float[].
     */
    public float[] getVectorAsFloats() {
        if (vectorData == null || vectorData.length == 0) {
            return new float[0];
        }
        java.nio.ByteBuffer buffer = java.nio.ByteBuffer.wrap(vectorData);
        float[] values = new float[vectorData.length / 4];
        for (int i = 0; i < values.length; i++) {
            values[i] = buffer.getFloat();
        }
        return values;
    }
}
