package com.semanticvault.model;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Represents a high-dimensional vector embedding generated by an embedding model.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class VectorEmbedding {

    private Long id;

    @NotBlank(message = "Model name cannot be blank")
    private String modelName;

    @Min(value = 1, message = "Dimensions must be at least 1")
    private int dimensions;

    @NotEmpty(message = "Vector array cannot be empty")
    private float[] vector;

    @NotNull(message = "Creation timestamp is required")
    private LocalDateTime createdAt;
}
