package com.semanticvault.algorithms.common;

import com.semanticvault.model.AlgorithmType;
import com.semanticvault.model.SearchRequest;
import com.semanticvault.model.SearchResponse;

import java.util.EnumMap;
import java.util.Map;
import java.util.Optional;

/**
 * Manages registration and routing of various search strategies.
 * Delegates the search request execution to the selected strategy.
 */
public class SearchContext {

    private final Map<AlgorithmType, SearchStrategy> strategies;

    public SearchContext(Map<AlgorithmType, SearchStrategy> strategies) {
        this.strategies = new EnumMap<>(strategies);
    }

    /**
     * Executes search by locating the appropriate strategy.
     *
     * @param request search query configuration
     * @return search response generated by the strategy
     * @throws SearchException if strategy is not registered or validation fails
     */
    public SearchResponse search(SearchRequest request) {
        if (request == null) {
            throw new SearchException("Search request cannot be null");
        }

        AlgorithmType type = request.getAlgorithm();
        if (type == null) {
            throw new SearchException("Search algorithm type is required");
        }

        SearchStrategy strategy = Optional.ofNullable(strategies.get(type))
                .orElseThrow(() -> new SearchException("Unavailable search algorithm strategy: " + type));

        return strategy.search(request);
    }
}
