package com.lumora.algorithms.common;

import com.lumora.model.AlgorithmType;
import com.lumora.model.SearchRequest;
import com.lumora.model.SearchResponse;

import java.util.EnumMap;
import java.util.Map;
import java.util.Optional;

/**
 * Manages registration and routing of various search strategies.
 * Delegates the search request execution to the selected strategy.
 */
public class SearchContext {

    private final Map<AlgorithmType, SearchStrategy> strategies;
    private final com.lumora.repository.VectorStore vectorStore;

    public SearchContext(Map<AlgorithmType, SearchStrategy> strategies, com.lumora.repository.VectorStore vectorStore) {
        this.strategies = new EnumMap<>(strategies);
        this.vectorStore = vectorStore;
    }

    /**
     * Executes search by locating the appropriate strategy.
     *
     * @param request search query configuration
     * @return search response generated by the strategy
     * @throws SearchException if strategy is not registered or validation fails
     */
    public SearchResponse search(SearchRequest request) {
        if (request == null) {
            throw new SearchException("Search request cannot be null");
        }

        AlgorithmType type = request.getAlgorithm();
        if (type == null) {
            throw new SearchException("Search algorithm type is required");
        }

        if (type == AlgorithmType.AUTO) {
            int size = vectorStore.findAll(request.getWorkspaceId()).size();
            if (size < 50) {
                type = AlgorithmType.BRUTE_FORCE;
            } else if (size < 500) {
                type = AlgorithmType.KD_TREE;
            } else {
                type = AlgorithmType.HNSW;
            }
        }

        final AlgorithmType resolvedType = type;
        SearchStrategy strategy = Optional.ofNullable(strategies.get(resolvedType))
                .orElseThrow(() -> new SearchException("Unavailable search algorithm strategy: " + resolvedType));

        SearchResponse response = strategy.search(request);
        // Explicitly set the resolved strategy type in the response if it was AUTO
        if (request.getAlgorithm() == AlgorithmType.AUTO) {
            response.setAlgorithm(resolvedType);
        }
        return response;
    }
}
